[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
Nikola = { extras = ["extras"], version = "*" }
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
